// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default (req, res) => {
  // Open Chrome DevTools to step through the debugger!
  // debugger;
  const jobs = [
    {
      id: 1,
      company_name: 'Honeywell technology solutions lab',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'Software Engineer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 2,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 3,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'senior progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 4,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'manager',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 5,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'senior manager',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 6,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'director',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 7,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'share holder',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 8,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 9,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 10,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 11,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 12,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 13,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 14,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 15,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 16,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 17,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
    {
      id: 18,
      company_name: 'EDC creative technology',
      company_address: '#189,Ravi nagar,gokul road hubli',
      location: 'hubli',
      job_title: 'juneer progmrammer',
      job_description: 'job description',
      tags: ['software', 'architect', 'react', 'angular'],
      experiance_range: '1-5',
      salary_range: ['50000-500500'],
      phone: 9986407307,
      email: 'manjunath@gmail.com',
      notice_period: '15 days',
    },
  ];
  res.status(200).json({ jobs: jobs });
};
